In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep=dataset[['age','bmi','children','sex_male', 'smoker_yes']]

In [6]:
dep=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
#StandardScaler for X_train
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [9]:
#StandardScaler for y_train
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 28
BMI: 33.75
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [11]:
preinput=sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

C:\anaconda 3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [12]:
preinput

array([[-0.81907079,  0.48098694,  0.76341038,  1.02378711,  1.98149332]])

In [13]:
loaded_model=pickle.load(open("finalized_model_Decision_tree.sav",'rb'))
result=loaded_model.predict(preinput)

C:\anaconda 3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


In [14]:
result

array([12829.4551])

In [15]:
preoutput=scy.inverse_transform([result])

In [16]:
preoutput

array([[1.52347134e+08]])